name: Multi-Job Workflow with Unique Caches

on:
  workflow_dispatch:  # Ручний запуск

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Cache (if exists)
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_1

      - name: Run Job 1 - Generate Files
        run: |
          mkdir -p /tmp/workflow_cache
          echo "Job 1 output file" > /tmp/workflow_cache/job_1_output.txt
          sleep 5  # Симуляція затримки

      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_1

  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Cache (job_1 + job_2)
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_1
          restore-keys: |
            shared-cache-job_1

      - name: Run Job 2 - Process Job 1 Output
        run: |
          cat /tmp/workflow_cache/job_1_output.txt > /tmp/workflow_cache/job_2_output.txt
          echo "Job 2 processed data" >> /tmp/workflow_cache/job_2_output.txt
          sleep 5  # Симуляція затримки

      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_2

  job_3:
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Cache (job_1 + job_2 + job_3)
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_2
          restore-keys: |
            shared-cache-job_1
            shared-cache-job_2

      - name: Run Job 3 - Use Previous Outputs
        run: |
          cat /tmp/workflow_cache/job_1_output.txt /tmp/workflow_cache/job_2_output.txt > /tmp/workflow_cache/job_3_output.txt
          echo "Job 3 done" >> /tmp/workflow_cache/job_3_output.txt
          sleep 5  # Симуляція затримки

      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_3

  job_4:
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Cache (job_1 + job_2 + job_4)
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_2
          restore-keys: |
            shared-cache-job_1
            shared-cache-job_2

      - name: Run Job 4 - Use Previous Outputs
        run: |
          cat /tmp/workflow_cache/job_1_output.txt /tmp/workflow_cache/job_2_output.txt > /tmp/workflow_cache/job_4_output.txt
          echo "Job 4 done" >> /tmp/workflow_cache/job_4_output.txt
          sleep 5  # Симуляція затримки

      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: /tmp/workflow_cache
          key: shared-cache-job_4
